<?php

declare(strict_types=1);

/*
 * Optional telemetry texts (RF-PD-12, ADR-020, ADR-023, task 5.10).
 *
 * WRITTEN FOR THE CUSTOMER. See the Spanish catalogue for the reasoning: the
 * decision to enable telemetry is taken with the field list in front of you,
 * and nothing here suggests that enabling it is recommended or that leaving it
 * off has any consequence.
 */

return [

    'title' => 'Installation telemetry',

    'state' => [
        'enabled' => 'ENABLED. A document like the one below is sent once a week.',
        'disabled' => 'NOT ENABLED. Nothing is sent, and the product works exactly the same.',
    ],

    'blocked' => [
        'disabled_by_configuration' => 'TELEMETRY_ENABLED is false, which is the product default.',
        'endpoint_not_configured' => 'TELEMETRY_ENDPOINT is empty: no destination is configured.',
        'endpoint_not_https' => 'The destination must start with https://. A destination without encryption is rejected as if there were none: the document would travel in the clear across your network.',
        'not_in_license' => 'Your licence does not include telemetry, or it has expired. Nothing else changes: telemetry is an accessory feature.',
    ],

    'document' => [
        'header' => 'This is EXACTLY what would be sent, field by field:',
        'footer' => 'Every field is explained in docs/cliente/configuracion.md, section «3 quinquies. Telemetria».',
        'never' => 'It never carries names, e-mail addresses, employee codes, clock-in times, server paths, your installation URL or the company name on your licence.',
    ],

    'identity' => [
        'label' => 'Identifier of this installation',
        'explanation' => 'A random number generated by your own installation. It is not derived from your licence or your name. Delete :path and a new one is minted.',
        'provisional' => 'THIS IDENTIFIER IS PROVISIONAL: looking leaves no trace, so nothing has been stored yet. The definitive one is minted and written to :path on the first delivery.',
    ],

    'history' => [
        'never' => 'No delivery has been attempted yet.',
        'last_attempt' => 'Last attempt:     :at',
        'last_success' => 'Last successful delivery: :at',
        'last_failure' => 'Last failure:     :failure',
    ],

    'send' => [
        'skipped' => 'Nothing was sent, and nothing was built.',
        'delivered' => 'Delivered (status :status, attempts: :attempts).',
        'failed' => 'Could not be delivered (:failure, attempts: :attempts). Nothing to worry about: it will be retried next week and the product works the same.',
    ],

    'how_to' => [
        'enable' => 'To enable it, set TELEMETRY_ENABLED=true and TELEMETRY_ENDPOINT=<address> in your .env.',
        'disable' => 'To disable it, set TELEMETRY_ENABLED=false in your .env. Nothing else is needed.',
        'send' => 'To send it right now:  php artisan product:telemetry --send',
    ],

];
