/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sonda de vida
         * @description Indica que el proceso responde y **con que version esta desplegado**
         *     (documento 02 §10.5): es lo que permite correlacionar una incidencia con
         *     una version concreta cuando el cliente llama por telefono.
         *
         *     No consulta base de datos, ni Redis, ni disco. Una sonda de vida que toca
         *     dependencias reinicia el contenedor cuando lo que esta caido es PostgreSQL,
         *     que es exactamente el fallo que no se quiere. Para eso esta `/api/v1/ready`.
         *
         *     **Publica y sin autenticacion**, como toda sonda de vida: el orquestador la
         *     consulta antes de que exista sesion alguna. Exponerla fuera de la red del
         *     cliente es una decision de Nginx, no de la aplicacion.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sonda de disponibilidad
         * @description Indica si la instancia puede aceptar trafico: comprueba las dependencias de
         *     las que depende una peticion real. Es la sonda que gobierna el despliegue
         *     sin parada (RNF-D-04) y la comprobacion posterior a una actualizacion
         *     (RF-PD-10).
         *
         *     **No detalla que dependencia ha fallado.** El diagnostico por componente
         *     vive en el paquete de diagnostico y en la comprobacion de salud
         *     posinstalacion (RF-PD-09, RF-PD-13), que son acciones autenticadas del
         *     administrador. Una sonda publica que enumera los servicios caidos es un
         *     mapa gratuito de la instalacion.
         */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar un escaneo de credencial en el quiosco
         * @description Registra el escaneo de una tarjeta QR en un quiosco autenticado (RF-AT-01) y
         *     devuelve al empleado lo que el quiosco tiene que enseñarle: nombre, accion,
         *     hora y acumulado de la jornada (RF-AT-05).
         *
         *     **Que decide el servidor.** Si el empleado no tiene turno abierto, el escaneo
         *     abre uno; si lo tiene, lo cierra (RF-AT-02, RF-AT-03). El cliente no decide la
         *     accion: la deduce el agregado `WorkDay`. Lo unico que el cliente puede aportar
         *     es la **intencion** (`intent`), porque con la pausa modelada como dos tramos
         *     (ADR-024) un `break_start` y un `clock_out` son indistinguibles para el
         *     servidor, y sin ese dato la jornada a la que se atribuye el tramo siguiente
         *     se calcula mal cuando la pausa cruza medianoche.
         *
         *     **Idempotencia (regla dura 8, RF-AT-07).** El `scan_id` lo genera el cliente
         *     (UUID v7) y es la clave de idempotencia. Reenviar el mismo `scan_id` devuelve
         *     la respuesta original —el mismo cuerpo y el mismo codigo—, nunca un duplicado
         *     ni un error. Es lo que hace segura la sincronizacion de la cola offline.
         *
         *     **Dos marcas de tiempo (regla dura 9, RF-AT-09).** `occurred_at` es el momento
         *     real del escaneo y puede venir de la cola offline con dias de retraso; el
         *     servidor añade `recorded_at`, el momento de recepcion. **El registro legal usa
         *     `occurred_at`.**
         *
         *     **Rechazos indistinguibles (regla dura 17, RS-03, RF-QR-02).** Un escaneo que
         *     no se puede registrar devuelve SIEMPRE la misma respuesta —`422` con
         *     `urn:kronoqr:problem:scan-rejected`— y consume el mismo tiempo, ya sea porque
         *     el prefijo no es `FH1`, porque la clave de firma es desconocida, porque la
         *     firma no valida, porque la credencial esta revocada o porque el empleado no
         *     esta activo. La causa concreta solo existe en `scan_events.result` y en el log
         *     del servidor. Por eso `qr_payload` **no declara `pattern`**: un patron en el
         *     contrato convertiria «formato invalido» en un `400` distinguible de un `422`,
         *     que es la misma fuga que el codigo se cuida de no cometer.
         *
         *     **El quiosco no espera a esta respuesta** (regla dura 19, documento 02 §6).
         *     Confirma al empleado en local en menos de 300 ms y encola; esta llamada
         *     sincroniza. Un fallo de red no puede impedir fichar.
         */
        post: operations["recordScan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Health
         * @description Estado de vida del proceso y version desplegada.
         */
        Health: {
            /**
             * @description Unico valor posible. Si el proceso no esta vivo, no responde.
             * @enum {string}
             */
            status: "ok";
            /**
             * @description Version SemVer desplegada (§10.5). Es lo que permite correlacionar una
             *     incidencia con una version concreta sin entrar por SSH al servidor del
             *     cliente.
             * @example 1.4.2
             */
            version: string;
        };
        /**
         * Readiness
         * @description Disponibilidad de la instancia para aceptar trafico.
         */
        Readiness: {
            /**
             * @description Unico valor posible en un `200`. La no disponibilidad se expresa con el
             *     codigo `503`, que es lo unico que lee un orquestador.
             * @enum {string}
             */
            status: "ready";
        };
        /**
         * ScanId
         * Format: uuid
         * @description Identificador del escaneo, **UUID v7 generado en el cliente**. Es la clave de
         *     idempotencia (regla dura 8).
         *
         *     El patron exige la version 7 a proposito: v7 es ordenable temporalmente, lo
         *     que mantiene la localidad del indice de `scan_events` y evita la
         *     fragmentacion que produciria un v4 aleatorio con millones de filas
         *     (documento 02 §6). Un v4 aqui es un fallo del cliente, no un caso a tolerar.
         * @example 0199f0c2-1f4a-7c3e-9b21-4d5e6f7a8b90
         */
        ScanId: string;
        /**
         * UtcTimestamp
         * Format: date-time
         * @description Instante en UTC con sufijo `Z` (regla dura 3). El patron rechaza los desfases
         *     explicitos (`+02:00`) y las horas sin zona: aceptarlos convertiria la zona
         *     horaria en un dato del cliente, y con turnos nocturnos y cambio de hora eso
         *     es una jornada mal atribuida.
         * @example 2026-08-14T05:58:31Z
         */
        UtcTimestamp: string;
        /**
         * ScanIntent
         * @description Intencion declarada por el empleado en el quiosco. `auto` deja que el servidor
         *     deduzca la accion por el estado de la jornada, y es el comportamiento de
         *     siempre: omitir el campo equivale a `auto` y no cambia nada (aditivo, ADR-012).
         *
         *     `break_start` y `break_end` existen porque la pausa son dos tramos (ADR-024) y
         *     el servidor no puede distinguir un inicio de pausa de un fin de turno. Solo
         *     tienen efecto si el fichaje de pausa esta habilitado en el centro (RF-AT-12).
         * @default auto
         * @enum {string}
         */
        ScanIntent: "auto" | "break_start" | "break_end";
        /**
         * ScanAction
         * @description Accion que el servidor ha aplicado. La decide el agregado `WorkDay`, no el
         *     cliente. El quiosco la usa para el feedback visual y sonoro diferenciado
         *     (RF-AT-05).
         * @enum {string}
         */
        ScanAction: "clock_in" | "clock_out" | "break_start" | "break_end";
        /**
         * ScanRequest
         * @description Escaneo de una credencial en un quiosco.
         */
        ScanRequest: {
            scan_id: components["schemas"]["ScanId"];
            /**
             * @description Momento real del escaneo, medido por el reloj del dispositivo. Puede venir
             *     de la cola offline con dias de retraso. **Es la marca que usa el registro
             *     legal** (regla dura 9, RF-AT-09).
             *
             *     Un desfase de reloj por encima del umbral no rechaza el fichaje: se acepta,
             *     se marca como incidencia y se avisa en el quiosco (RF-AT-10). Nunca se
             *     pierde una jornada por un problema tecnico ajeno al empleado.
             */
            occurred_at: components["schemas"]["UtcTimestamp"];
            /**
             * @description Payload leido del QR, en el formato `FH1.<key_id>.<token>.<sig>`
             *     (documento 02 §5.1). Opaco: sin PII y sin identificadores secuenciales.
             *
             *     **Sin `pattern` a proposito** (regla dura 17). Un patron aqui haria que un
             *     payload con el prefijo cambiado devolviera `400` en vez del `422` generico,
             *     y con eso el contrato distinguiria «formato invalido» de «credencial
             *     desconocida»: justo lo que §5.2 obliga a no distinguir. Los limites de
             *     longitud son proteccion de recursos, no validacion de formato, y no
             *     dependen del contenido.
             * @example FH1.a3.7QK2mXpR9vLdN4tZbYcF1w.k9Xm2pQrT5vN8wLa
             */
            qr_payload: string;
            intent?: components["schemas"]["ScanIntent"];
        };
        /**
         * ScanAccepted
         * @description Lo que el quiosco necesita para confirmar al empleado, y **nada mas**
         *     (RF-AT-05). No es un endpoint de consulta: un token de quiosco no ve aqui
         *     identificadores del empleado, ni su departamento, ni sus tramos, ni nada que
         *     no quepa en la pantalla de confirmacion. `additionalProperties: false` lo
         *     convierte en una comprobacion automatica y no en una buena intencion.
         */
        ScanAccepted: {
            scan_id: components["schemas"]["ScanId"];
            action: components["schemas"]["ScanAction"];
            /**
             * @description Nombre en su forma minima: nombre de pila e inicial del primer apellido.
             *     Es exactamente lo que devuelve `roster:read` (§7.3), y por el mismo motivo:
             *     un token de quiosco robado no debe reconstruir la plantilla del hotel.
             * @example Maria G.
             */
            employee_display_name: string;
            /**
             * Format: date
             * @description Jornada a la que se atribuye el tramo. **No es la fecha de `occurred_at`**:
             *     un turno de 22:00 a 06:00 es un unico tramo atribuido a la jornada de su
             *     hora de inicio (RN-05, ADR-006, regla dura 4). El quiosco la muestra para
             *     que el acumulado no resulte incomprensible en el turno de noche.
             * @example 2026-08-13
             */
            work_date: string;
            /** @description Eco del momento real del escaneo, tal y como ha quedado registrado. */
            occurred_at: components["schemas"]["UtcTimestamp"];
            /**
             * @description Momento en que el servidor recibio el escaneo (regla dura 9). Junto con
             *     `occurred_at` permite al quiosco medir su propio desfase de reloj y
             *     avisar, que es la mitad de cliente de RF-AT-10.
             */
            recorded_at: components["schemas"]["UtcTimestamp"];
            /**
             * @description Minutos acumulados en la jornada `work_date`, **recalculados**, nunca
             *     incrementados (RN-06, ADR-007, regla dura 7).
             *
             *     Se llama asi y no «minutos de hoy» porque en un turno nocturno la jornada
             *     y el dia natural no coinciden, y un nombre que diga «hoy» acabaria
             *     pintando el total del dia equivocado. No lleva `maximum`: la jornada
             *     maxima es un umbral del perfil de cumplimiento, no una constante del
             *     producto (regla dura 14, RN-11).
             * @example 482
             */
            worked_minutes: number;
        };
        /**
         * Problem
         * @description Error en el formato `application/problem+json` (RFC 9457). El cliente
         *     interpreta `type`, que es un URN estable; `title` y `detail` son texto para
         *     personas y pueden cambiar sin que eso rompa a nadie.
         */
        Problem: {
            /**
             * Format: uri
             * @description URN estable del tipo de problema. Se usa un URN y no una URL porque la
             *     instalacion vive en el servidor del cliente, a menudo sin salida a
             *     internet: una URL que nadie puede abrir no documenta nada y ademas
             *     filtraria el host.
             * @example urn:kronoqr:problem:scan-rejected
             */
            type: string;
            /** @description Resumen legible del tipo de problema. */
            title: string;
            /** @description Codigo HTTP, repetido en el cuerpo como exige RFC 9457. */
            status: number;
            /** @description Explicacion para quien depura. El cliente no la muestra al usuario. */
            detail?: string;
            /**
             * Format: uri-reference
             * @description Referencia a la ocurrencia concreta, cuando aporta algo.
             */
            instance?: string;
        };
        /**
         * ValidationProblem
         * @description Problema con el detalle de los campos que incumplen el contrato. Solo aparece
         *     en errores de forma de la peticion, nunca en un rechazo de escaneo.
         */
        ValidationProblem: components["schemas"]["Problem"] & {
            /** @description Mensajes por campo, indexados por el nombre del campo. */
            errors: {
                [key: string]: string[];
            };
        };
        /**
         * ScanRejected
         * @description **La unica respuesta de rechazo de un escaneo.** Todos los campos estan fijados
         *     a un valor unico y no se admiten miembros adicionales, de modo que el contrato
         *     no ofrece ningun sitio donde alojar la causa: ni un codigo, ni un motivo, ni un
         *     matiz en el texto (regla dura 17, RS-03, RF-QR-02).
         *
         *     Que sea imposible es el punto. Una respuesta generica que dependiera de que
         *     nadie añada un campo «por comodidad de depuracion» duraria hasta la primera
         *     tarde de diagnostico.
         */
        ScanRejected: {
            /**
             * Format: uri
             * @enum {string}
             */
            type: "urn:kronoqr:problem:scan-rejected";
            /** @enum {string} */
            title: "Escaneo no valido";
            /** @enum {integer} */
            status: 422;
            /**
             * @description Texto fijo. No se traduce ni se detalla: el quiosco muestra su propio texto
             *     de i18n a partir de `type`, y cualquier variacion aqui seria un canal por
             *     el que distinguir causas.
             * @enum {string}
             */
            detail: "El escaneo no se ha podido registrar.";
            scan_id: components["schemas"]["ScanId"];
        };
    };
    responses: {
        /**
         * @description La peticion esta mal formada: falta un campo, un formato no es valido o la
         *     cabecera `Idempotency-Key` no coincide con `scan_id`. Es un fallo del
         *     cliente, y ninguna de sus causas dice nada sobre credenciales: el rechazo de
         *     un escaneo NUNCA llega por aqui, sino como `422`.
         */
        InvalidRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ValidationProblem"];
            };
        };
        /** @description Falta el token o no es valido. */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description El token es valido pero no tiene el ambito necesario, o la policy deniega el
         *     acceso a estos datos. Cada endpoint tiene su prueba de autorizacion negativa
         *     por rol (regla dura 18).
         */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /**
         * @description Se ha superado el limite de peticiones (§7.1). El cliente debe reintentar con
         *     retroceso exponencial; el quiosco ya lo hace por diseño y el empleado no se
         *     entera, porque su fichaje esta encolado en local desde el primer momento.
         */
        TooManyRequests: {
            headers: {
                /**
                 * @description Segundos que conviene esperar antes de reintentar.
                 * @example 2
                 */
                "Retry-After": number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /**
         * @description Clave de idempotencia de la escritura. **Debe coincidir con el `scan_id` del
         *     cuerpo**; si difieren, la peticion es invalida (`400`).
         *
         *     Va en cabecera ademas de en el cuerpo porque es la convencion que entienden
         *     los intermediarios HTTP y porque deja la intencion explicita en el borde,
         *     antes de deserializar nada. La garantia real la da el UNIQUE de
         *     `scan_events.scan_id` (regla dura 8), no la cabecera.
         * @example 0199f0c2-1f4a-7c3e-9b21-4d5e6f7a8b90
         */
        IdempotencyKey: components["schemas"]["ScanId"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description El proceso responde. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description La instancia acepta trafico. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
            /**
             * @description La instancia todavia no acepta trafico. El orquestador debe reintentar y
             *     no enviarle peticiones mientras tanto.
             */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    recordScan: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Clave de idempotencia de la escritura. **Debe coincidir con el `scan_id` del
                 *     cuerpo**; si difieren, la peticion es invalida (`400`).
                 *
                 *     Va en cabecera ademas de en el cuerpo porque es la convencion que entienden
                 *     los intermediarios HTTP y porque deja la intencion explicita en el borde,
                 *     antes de deserializar nada. La garantia real la da el UNIQUE de
                 *     `scan_events.scan_id` (regla dura 8), no la cabecera.
                 * @example 0199f0c2-1f4a-7c3e-9b21-4d5e6f7a8b90
                 */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequest"];
            };
        };
        responses: {
            /**
             * @description Escaneo registrado. Es tambien la respuesta de un reenvio con el mismo
             *     `scan_id`: identica a la original.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanAccepted"];
                };
            };
            400: components["responses"]["InvalidRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            /**
             * @description **Escaneo rechazado.** Respuesta unica, generica y de tiempo constante
             *     para toda causa de rechazo (regla dura 17, RS-03, documento 02 §5.2).
             *     El cuerpo esta fijado campo a campo en el esquema y no admite miembros
             *     adicionales: el contrato hace **imposible** describir la causa, que es
             *     el unico modo de garantizar que nadie la filtre por descuido.
             *
             *     El quiosco muestra su propio texto de i18n a partir de `type`. Nunca
             *     debe mostrar `title` ni `detail`, que son texto para quien depura.
             */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ScanRejected"];
                };
            };
            429: components["responses"]["TooManyRequests"];
        };
    };
}
